### ISSUE TITLE
Improve spacing on mobile landscape mode

### ISSUE THREAD

**Issue by aredshift** [aquapants/website#3]
When mobile is flipped to landscape mode the links-bar looks kind of crowded. I think we could improve the proportions (possibly decrease the margin between the header and the quote)

![image](https://github.com/aquapants/website/assets/123187978/6b2f5b8f-a925-48d6-b271-5e0fb2357f8c)

**Comment by mrbjnb** [comment]
I want to try out but I am not sure about the requirement you mentioned. Is it adjusting the margin so the header and the quotes spacing far away from each other?

**Comment by aredshift** [comment]
Hi @mrbjnb, thanks for offering to contribute! I apologize for the lack of clarity - we're a small group of friends getting started on a few fun projects together and we just put together this website to be a hub for our group projects, so we haven't formalized an issue or PR template yet. 

You're most welcome to take on this issue if you'd like to help!

To clarify the issue: the pink-colored links bar at the bottom of the page is right up against the bottom of the screen, and I think it would look better if there was more empty space on the bottom. I think this empty space should come from between the header and the quote.

One thing to keep in mind is that we're trying to keep the website design [responsive](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design), so while making this change, please be sure to test it on different sizes of screen. If you're new to these concepts and want some more direction I'd be happy to give you a few pointers. Otherwise I'll assign this issue to you and leave you to it!

**Comment by mrbjnb** [comment]
Oh I see, thank you for the assignment, I will try to figure it out. 🫡

**Comment by mrbjnb** [comment]
![image](https://github.com/aquapants/website/assets/80120114/75b03bc2-436f-474b-ac0d-26b889cd37f6)
Is this good enough? @aredshift

**Comment by mrbjnb** [comment]
Also I should commit it to the dev branch right? I am new to GitHub development.

**Comment by mrbjnb** [comment]
I have no idea how to create a pull request, can you help me?

**Comment by aredshift** [comment]
Hey @mrbjnb! Great start, the links-bar looks like it has more breathing room at the bottom of the page now. One note: I'd like to see the header & subheader look bigger on the screen and the quote look smaller.

As for submitting a pull request, here is some helpful documentation for best-practices for contributing to open source projects on Github: [https://docs.github.com/en/get-started/quickstart/contributing-to-projects](https://docs.github.com/en/get-started/quickstart/contributing-to-projects).

Basically what you'd normally do is:
1. Create a [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) of our project under your ownership (eg. mrbjnb/website, but you can rename it something different if you'd like)
2. Clone your fork
3. Create a branch for your work from the forked repo, for example `3-improve-landscape-spacing` (but you can name it what you like)
4. Push your changes to your fork
5. Submit a PR from your fork's feature branch to our project's `main` branch

Then we can review/update and then merge it when everything looks good!

One convoluting factor is that I'm guessing you've cloned our repo to make and test the change. Since this project is pretty small and I imagine you don't have a complex git commit history, you should simply be able to copy and paste the contents of the files you changed and then re-commit them to your fork's feature branch. If however you want to preserve your commit history or just want to learn how to move a branch between repositories, lmk and I will give you some instructions.

In the future, we'll be sure to make a [contributing instructions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file for our repo so this is all much more straightforward. :)

Thanks again for helping out and asking questions!

**Comment by mrbjnb** [comment]
Oh I see, thank you for your details answered. I will improve it and try to make a pull request soon.
